#!/bin/sh

# This script is used to update the filenametags for lookupfile plugin, and the
# ctags & cscope database
# Author  : Easwy Yang
# Homepage: http://easwy.com/
# Date    : Mon Oct 25 16:01:48 CST 2010

# Create folder  to save tags
TAGDIR=TAGDIR
mkdir -p ${TAGDIR}

# Default project type
PRJ_TYPE=cpp

case ${PRJ_TYPE} in
    java)
    SRC_DIR="src"
    find 		`pwd`                       \
                -name ".svn" -prune         \
                -or -name ".git" -prune     \
                -or -name "*.java"          \
                > ${TAGDIR}/cscope.files
    ;;
    cpp)
    SRC_DIR="."
    find 		`pwd`						\
                -name ".svn" -prune         \
                -or -name ".git" -prune     \
                -or -name "*.h"             \
                -or -name "*.hpp"             \
                -or -name "*.cpp"           \
                -or -name "*.cc"            \
                -or -name "*.c"            \
                > ${TAGDIR}/cscope.files
    ;;
    *)
    ;;
esac

# generate tag file for lookupfile plugin
echo "!_TAG_FILE_SORTED	2	/2=foldcase/" > ${TAGDIR}/filenametags
find 		`pwd`                       \
            -name ".svn" -prune         \
            -or -name ".git" -prune     \
            -or -type f                 \
            -printf "%f\t%p\t1\n"       \
            | sort -f >> ${TAGDIR}/filenametags

# Generate cscope database & tags
cd ${TAGDIR} && cscope -bkq -i cscope.files && ctags --c++-kinds=+p --fields=+iaS --extra=+q -L cscope.files

exit 0
